effectiveVocabulary/urls.py
from django.contrib import admin
from django.urls import path, include


#to upload pdf file
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('tables.urls')),
    path('', include('learnWithDocumentation.urls')),

  #to upload pdf files
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG : 
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tables/urls.py
from django.urls import path

#to protect path
from django.contrib.auth.decorators import login_required

from . import views

#to put name to all set of paths
app_name = 'tables_app' # 'tables_app' : is used this name_app by convention

urlpatterns = [
    path('titulo/<str:action_table>', login_required(views.CreateTitleTable.as_view()), name = 'title'),
    path('menu/<int:table_id>/<str:title>', login_required(views.AccessMenuTable.as_view()), name = 'menu'),
    path('crear-vocabulario/<int:table_id>/<str:title>', login_required(views.CreateVocabularyTable.as_view()), name = 'create_vocabulary'),
    path('lista-de-palabras/<int:table_id>/<str:title>', login_required(views.WordListView.as_view()), name = 'word_list'),
    path('coleccion-tablas/', login_required(views.TableCollectionView.as_view()), name = 'table_collection'),
    path('otras-tablas/', login_required(views.OtherTables.as_view()), name = 'other_tables'),
    path('bienes/<int:table_id>/<str:asset>', login_required(views.AssetsTable.as_view()), name = 'assets'),
    path('actualizar/<pk>/', login_required(views.UpdateTable.as_view()), name = 'updatetable'),
    path('elimninar-tabla/<pk>/', login_required(views.RemoveTable.as_view()), name = 'removetable'),
    path('descarga/<str:pdfpath>', login_required(views.download_pdf), name = 'download'),
    path('subir/', login_required(views.uploadfile_view), name = 'upload'),

] 

user/urls.py
#imports hierarchy
""" 
    1. imports of python
    2. imports of django
    3. my imports
 """

from django.urls import path

# to use login provided by default by django, import two functions  
                                        # login: it continas login to start session, but it was deprecated, instead to useLoginView
                                        # logout_then_login : it containts the logic to close session
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'user_app'

urlpatterns = [
    path('', views.LoginView.as_view(), name = 'log_in'),
    #path() allows to send aditional args to views asociated in the specify path
    # path('', LoginView.as_view(template_name='log_in.html'), name = 'log_in'),
    path('iniciar-sesion/', views.LoginView.as_view(), name = 'log_in'),
    path('registro/', views.register, name = 'register'),
    path('usuario/', views.user, name = 'user'),
    path('cerrar-sesion/', views.user_logout, name = 'logout'),
    path('lista-idiomas/', views.LanguagesUserListView.as_view(), name = 'languagesuser'),
    path('detalle-usuario/<pk>', views.DetailUserDetailView.as_view(), name = 'detailuser'),

]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/templates/layouts/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles_user.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles-app-tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>
<body>
    <header>
        <h1>VOCABULARIO EFECTIVO</h1>
        {% if user.email %}
            <div class="user-control">
                <img src="{% static 'img/user2.png' %}" alt="">

                <ul>
                    <li class="logout"><a href="{% url 'user_app:logout' %}">Cerrar sesión</a></li>
                </ul>
        
            </div>
        {% endif %}
    </header>

    <section class="main-container">
        <nav class="container-menu">
            <ul>
                {% if user.email %}           
                    <!-- <li><a href="{% url 'user_app:user' %}">Usuario</a></li> -->
                    <li><a href="{% url 'tables_app:title' action_table='set_table' %}">Nueva Tabla</a></li>
                    <li><a href="{% url 'tables_app:table_collection' %}">Mis tablas</a></li>
                    <li><a href="{% url 'tables_app:other_tables' %}">Otras tablas</a></li>

                    <!-- learning django -->
                    <li><a href="{% url 'user_app:languagesuser' %}">Lenguajes usuario</a></li>
                    <li><a href="{% url 'user_app:detailuser' pk=user.id %}">Detalle usuario</a></li>
                {% else %}
                    <li><a href="{% url 'user_app:log_in' %}">Iniciar Sesión</a></li>
                    <li><a href="{% url 'user_app:register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </nav>
    
        <div class="container-tables">
            <div class="subcontainer-tables">
                {% block main_content %}

                {% endblock %}
            </div>
            
        </div>
    </section>
</body>
</html>