effectiveVocabulary/urls.py
from django.contrib import admin
from django.urls import path, include


#to upload pdf file
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('tables.urls')),
    path('', include('learnWithDocumentation.urls')),

  #to upload pdf files
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG : 
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tables/urls.py
from django.urls import path

#to protect path
from django.contrib.auth.decorators import login_required

from . import views

#to put name to all set of paths
app_name = 'tables_app' # 'tables_app' : is used this name_app by convention

urlpatterns = [
    path('titulo/<str:action_table>', login_required(views.CreateTitleTable.as_view()), name = 'title'),
    path('menu/<int:table_id>/<str:title>', login_required(views.AccessMenuTable.as_view()), name = 'menu'),
    path('crear-vocabulario/<int:table_id>/<str:title>', login_required(views.CreateVocabularyTable.as_view()), name = 'create_vocabulary'),
    path('lista-de-palabras/<int:table_id>/<str:title>', login_required(views.WordListView.as_view()), name = 'word_list'),
    path('coleccion-tablas/', login_required(views.TableCollectionView.as_view()), name = 'table_collection'),
    path('otras-tablas/', login_required(views.OtherTables.as_view()), name = 'other_tables'),
    path('bienes/<int:table_id>/<str:asset>', login_required(views.AssetsTable.as_view()), name = 'assets'),
    path('actualizar/<pk>/', login_required(views.UpdateTable.as_view()), name = 'updatetable'),
    path('elimninar-tabla/<pk>/', login_required(views.RemoveTable.as_view()), name = 'removetable'),
    path('descarga/<str:pdfpath>', login_required(views.download_pdf), name = 'download'),
    path('subir/', login_required(views.uploadfile_view), name = 'upload'),

] 

user/urls.py
#imports hierarchy
""" 
    1. imports of python
    2. imports of django
    3. my imports
 """

from django.urls import path

# to use login provided by default by django, import two functions  
                                        # login: it continas login to start session, but it was deprecated, instead to useLoginView
                                        # logout_then_login : it containts the logic to close session
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'user_app'

urlpatterns = [
    path('', views.LoginView.as_view(), name = 'log_in'),
    #path() allows to send aditional args to views asociated in the specify path
    # path('', LoginView.as_view(template_name='log_in.html'), name = 'log_in'),
    path('iniciar-sesion/', views.LoginView.as_view(), name = 'log_in'),
    path('registro/', views.register, name = 'register'),
    path('usuario/', views.user, name = 'user'),
    path('cerrar-sesion/', views.user_logout, name = 'logout'),
    path('lista-idiomas/', views.LanguagesUserListView.as_view(), name = 'languagesuser'),
    path('detalle-usuario/<pk>', views.DetailUserDetailView.as_view(), name = 'detailuser'),

]

tables/models.py
from django.db import models

from django.contrib.auth.models import User

# CKEDITOR
from ckeditor.fields import RichTextField

class Table(models.Model) :
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE) 
    title = models.CharField(max_length = 255)
    link = models.CharField(max_length = 255, null = True, blank = True)
    pdf_doc = models.FileField(null = True, blank = True, upload_to='pdf')

class Word(models.Model) :
    table = models.ForeignKey(Table, null = True, blank=True, on_delete = models.CASCADE) # on_delete=models.CASCADE : it allows to remove for example when user will be removed, register for comment with user removed, also will be removed
    english_word = models.CharField(max_length = 1000)
    spanish_word = models.CharField(max_length = 1000)
    inverosimil_relation = RichTextField(max_length = 2000)
    # table = models.OneToOneField(Table, null = True, blank = True, on_delete = models.PROTECT)

tables/forms.py
from django import forms

# for validations
from django.core import validators

from django.forms import ModelForm
from .models import Word, Table

from ckeditor.fields import RichTextField

class TableForm(ModelForm):
    # to remove required in link field
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['link'].required = False

    class Meta:
        model = Table
        fields = ['title', 'link', 'pdf_doc']

        labels = {
            'title' : 'Título de tabla',
            'link' : 'Link del sitio web para el que creas la tabla(opcional)',
            'pdf_doc' : 'Archivo PDF para el que creas la tabla(opcional)',
        }
        widgets = {
            'pdf_doc' : forms.FileInput(
                attrs = {
                    'class':'pdf_doc'
                }
            )
        }

class WordForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(WordForm, self).__init__(*args, **kwargs)
        # Making inverosimil_relation required
        self.fields['inverosimil_relation'].required = False

    class Meta:
        model = Word
        fields = ['english_word', 'spanish_word', 'inverosimil_relation']

        # removing label tags
        labels = {
            'english_word' : '',
            'spanish_word' : '',
            'inverosimil_relation' : '',
        }
        

        

tables/views.py
# ============================================== documentation recomended:  http://ccbv.co.uk/

from django.shortcuts import render, redirect

#http response
from django.http import HttpResponse, Http404

# importing generic Views
from django.views.generic import View, TemplateView, ListView, CreateView, UpdateView, DeleteView 

# models
from tables.models import Word, Table
from user.models import User

#form
from tables.forms import WordForm, TableForm

#to upload pdf file
from django.core.files.storage import FileSystemStorage

# to dowload pdf
from django.http import FileResponse

#to redirect with CreateView
from django.urls import reverse, reverse_lazy

import os
# ************************************************* it doesn´t serve now 

def obtain_owner_table(table_id):
    table = Table.objects.filter(id = table_id)
    owner_table_id = table[0].user_id
    print('----------------owner-------------------', table[0].user_id)
    return owner_table_id

class xxxTitleTable(TemplateView) : 
    template_name = 'table/title.html'

    def get(self, request, *args, **kwargs) :
        table_form = TableForm()  

        context = {
            'form': table_form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs): 

        if request.method == 'POST' :
            table_form = TableForm(request.POST, request.FILES)
            
            if table_form.is_valid():
                table = table_form.save(commit = False)
                table.user_id = request.user.id
                table.save()

            return redirect('app_name:menu', table_id = table.id, title = table.title)

class CreateTitleTable(CreateView):
    template_name = 'table/title.html'
    model = Table
    form_class = TableForm

    #if I want to pass all fields
    #fields = ('__all__')

    # to redirectionate after to save all data
    #success_url = '.' # . : redirect to the same path
    #success_url = reverse_lazy('tables_app:other_tables') #import to evit spaces in the param
    def get_success_url(self):
        return reverse_lazy('tables_app:menu', kwargs = {
            'table_id': self.object.id,
            'title':self.object.title
        })

    # CONCLUSION: never to make two saved in a single code
    # it is used when values entered were correct, it is done checking params established in models
    def form_valid(self, form): # form contain all data entered in the form
        form.instance.user = self.request.user

        # super : it is used to override method provided by django
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateTitleTable, self).get_context_data(**kwargs)
        context['action_table'] = self.kwargs['action_table']

        return context
     


class AccessMenuTable(TemplateView) :
    template_name = 'table/main menu.html'

    def obtainAssetsTable(self, table_id):
        assets = Table.objects.filter(id = table_id)
        return assets

    def get(self, request, *args, **kwargs) : 
        table_id = kwargs['table_id']
        title = kwargs['title']
        data_table = self.obtainAssetsTable(table_id)
        owner_table = obtain_owner_table(table_id)

        return render(request, self.template_name, {
            'table_id': table_id,
            'title': title,
            'pdf_doc':data_table[0].pdf_doc,
            'link':data_table[0].link,
            'owner_table':owner_table
        })

class xxxCreateVocabularyTable(View):
    #django know that method use : get, post, put, delete; it is thanks to dispacht() method

    def get(self, request, *args, **kwargs) : # **kwargs : keys of aditional arguments
        form = WordForm()
        table_id = kwargs['table_id']
        title = kwargs['title']    

        return render(request, 'table/create vocabulary.html', {
            'form': form,
            'table_id': table_id,
            'title':title
        })

    def post(self, request, *args, **kwargs):
        table_id = kwargs['table_id']
        title = kwargs['title']

        if request.method == 'POST' : 
            form = WordForm(request.POST)

            if form.is_valid() :
                #form contain all data saved in database
                                # commit = False : it evits make the first save to database
                form = form.save(commit = False) #save : to save data in database

                #accesing to an attribute of this model saved in database
                form.table_id = table_id
                form.save()

                return redirect('tables_app:create_vocabulary', table_id = table_id, title = title)
             
class CreateVocabularyTable(CreateView):
    template_name = 'table/create vocabulary.html'
    model = Word
    form_class = WordForm


    def get_context_data(self, **kwargs):
        owner_table_id = obtain_owner_table(self.kwargs['table_id'])

        context = super(CreateVocabularyTable, self).get_context_data(**kwargs)
        context['table_id'] = self.kwargs['table_id']
        context['title'] = self.kwargs['title']
        context['owner_table'] = owner_table_id

        return context

    #post is executed after to form_valid
    def _post(self, request): # request is used to get data sent by the form
        pass

    def form_valid(self, form):
        form.instance.table_id = self.kwargs['table_id']
        return super().form_valid(form)       

    def get_success_url(self):
        return reverse_lazy('tables_app:create_vocabulary', kwargs = {
            'table_id': self.kwargs['table_id'],
            'title': self.kwargs['title']
        })


#to use here ListView
class WordListView(ListView):
    #to specify name of model to get
    model = Word

    template_name = 'table/word list.html'
    
    #setting name of param to send to context
    context_object_name = 'word_collection'

    def get_queryset(self, *args, **kwargs) :
        table_id = self.kwargs['table_id']
        kword = self.request.GET.get('kword',)

        if kword:
            return Word.objects.filter(table_id = table_id, english_word = kword)

        return Word.objects.filter(table_id = table_id)
    
    #overwriting context
    def get_context_data(self, **kwargs):
        owner_table = obtain_owner_table(self.kwargs['table_id'])

        context = super(WordListView, self).get_context_data(**kwargs)
        context['table_id'] = self.kwargs['table_id']
        context['title'] = self.kwargs['title']
        context['owner_table'] = owner_table

        return context


class TableCollectionView(ListView) :
    template_name = 'table_collection/table_collection.html'
    context_object_name = 'tables'
    paginate_by = 10
    def get_queryset(self, *args, **kwargs) : 
        return Table.objects.filter(user_id = self.request.user.id)


class OtherTables(ListView) :
    model = Table
    template_name = 'table_collection/table_collection_other_users.html'

    # to paginate queries of database
    paginate_by = 10
    context_object_name = 'tables'

    def get_queryset(self, *args, **kwargs):
        return Table.objects.exclude(user_id = self.request.user.id)


class AssetsTable(View):
    template_name = 'table/assets table.html'     

    def obtain_pdf_path(self, datatable):
        pdfname = str(datatable[0].pdf_doc).split('/')
        pdfpath = ''

        if pdfname[0] != '':
            pdfpath = datatable[0].pdf_doc.path

        return pdfpath

    def get(self, request, *args, **kwargs):
        table_id = kwargs['table_id']
        asset = kwargs['asset']
        datatable = Table.objects.filter(id = table_id)
        owner_table_id = obtain_owner_table(self.kwargs['table_id'])

        pdfpath = self.obtain_pdf_path(datatable)

        context = {
            'title':datatable[0].title,
            'table_id':datatable[0].id,
            'link':datatable[0].link ,
            'asset':asset,
            'pdfpath':pdfpath,
            'owner_table':owner_table_id
        }
        return render(request, self.template_name, context)

class UpdateTable(UpdateView):
    template_name = 'table/title.html'
    model = Table
    form_class = TableForm
    #success_url = reverse_lazy('tables_app:assets')

    def adsfasdfget_context_data(self, **kwargs):
        context = super(UpdatePdfTable, self).get_context_data(**kwargs)

        context['table_id'] = self.kwargs['table_id']
        context['title'] = self.kwargs['title']

        return context

    #if an error 403 is through, it is an segurity error
    def get_success_url(self):
        project = self.object
        return reverse_lazy('user_app:user')    

    
class RemoveTable(DeleteView):
    model = Table
    template_name = 'table/remove table.html'
    success_url = reverse_lazy('tables_app:table_collection')

def download_pdf(request, pdfpath) :
    if os.path.exists(pdfpath):
        with open(pdfpath, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/pdf")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(pdfpath)
            return response
    raise Http404




def uploadfile_view(request):
    # https://docs.djangoproject.com/en/3.1/topics/http/file-uploads/
    if request.method == 'POST':
        f = request.FILES['file']
        fs = FileSystemStorage()
        filename, ext = str(f).split('.')
        file = fs.save(str(f), f)
        fileurl = fs.url(file)
        size = fs.size(file)

        return render(request, 'demo_upload_files.html', {
            'fileUrl':fileurl,
            'fileName':filename,
            'ext':ext,
            'size':size
        })
    else :
        return render(request, 'demo_upload_files.html',{})

tables/templates/table/assets table.html
{% extends 'table/main menu.html' %}

{% block content_table %}

    <div class="assets">
        {% if asset == 'pdf_doc' %}
            {% if pdfpath != '' %}
                <P>ENLACE: <a href="{% url 'tables_app:download' pdfpath=pdfpath %}">Descargar</a></P>
            {% else %}
                 <p>Esta tabla no tiene un documento PDF</p>

                
                {% if owner_table == user.id %}
                    <button class="update-table"><a href="{% url 'tables_app:updatetable' pk=table_id %}">Actualizar</a></button>
                {% endif %}

            {% endif %}


        {% else %}
            {% if link != None %}
                <P>ENLACE: <a href="{{link}}">sitio web</a></P>
            {% else %}
                <p>Esta tabla no tiene vínculo a un sitio web</p>

                {% if owner_table == user.id %}
                    <button class="update-table"><a href="{% url 'tables_app:updatetable' pk=table_id %}">Actualizar</a></button>
                {% endif %}
                
            {% endif %}
            
        {% endif %}
    </div>

{% endblock %}

tables/templates/table/create vocabulary.html
{% extends 'table/main menu.html' %}


{% block content_table %}
    <!-- <form action="{ url 'table' }{{box}}/{{user_id}}" method="POST"> : other way to pass params -->

    <div class="table-container">
        {% include 'includes/description_table.html' %}
        
        {% if owner_table == user.id %}
            <form class="form-of-words" action="" method="POST">
                {{ form.media }}
                {{ form.as_p }}
                
                <div class="button">
                    <input type="submit" value="Guardar">
                </div>

                <span>{% csrf_token %}</span>
            </form>

        {% endif %}
    </div>
    
{% endblock %}

tables/templates/table/main menu.html
{% extends 'layouts/layout.html' %}
{% load static %}

{% block main_content %}
    
    <h2 class="title-table">{{title|upper}}</h2>    

    {% include 'includes/menu vocabulary.html' %}

    {% block content_table %}

    {% endblock %}
    
    <script src="{% static 'js/content.js' %}"></script>
{% endblock %}

tables/templates/table/remove table.html
{% extends 'layouts/layout.html' %}

{% block main_content %}
    
    <h2 class="action-table">Estás seguro de eliminar esta tabla</h2>
    <h3 class="remove-warning">¿Estás seguro de eliminar esta tabla?</h3>
    <form class="form-table" action="" method="POST">
        {% csrf_token %}

        <input type="submit" value="Confirmar">

    </form>

{% endblock %}

tables/templates/table/title.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% block main_content %}
    
    {% if action_table == 'set_table' %}
        {% include 'includes/form set table.html' %}
        
    {% else %}
    
        {% include 'includes/form update table.html' %}
    {% endif %}

{% endblock %}

tables/templates/table/word list.html
{% extends 'table/main menu.html' %}

{% block content_table %}
    <div class="table-container">

        <!-- a token will be added to protect the url -->
        
        <form action="GET" class="form-search">
            {% csrf_token %}
            <input type="text" name="kword" placeholder="Buscar palabra en inglés de esta tabla" class="search-field">

            <button type="submit" class="search-button">Buscar</button>
        </form>


        {% include 'includes/description_table.html' %}
        
        <!-- after to use ListView, to iterate the elements use object_list -->
        <!-- {{object_list}} -->

        {% if word_collection|length > 0 %}
            {% for word in word_collection %}
                <ul class="word_list">
                    <li>{{word.english_word}}</li>
                    <li>{{word.spanish_word}}</li>
                    <li>{{word.inverosimil_relation|safe}}</li>
                </ul>
            {% endfor %}

        {% else %}
            <p class="without-words-message">No hay palabras disponibles para esta tabla</p>
        {% endif %}

    </div>

{% endblock %}